# Generated by Django 6.0 on 2026-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
