# Generated by Django 6.0 on 2026-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduit', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
