# Generated by Django 6.0 on 2026-09-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conduit', '0003_alter_user_bio_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='followed_users',
        ),
    ]
