# Generated by Django 6.0 on 2026-09-01 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduit', '0003_alter_user_bio_alter_user_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations = [
                migrations.RunSQL(
                    sql='ALTER TABLE conduit_user_following RENAME TO conduit_user_followed_users;',
                    reverse_sql='ALTER TABLE conduit_user_followed_users RENAME TO conduit_user_following;'
                )
            ],
            state_operations = [
                migrations.RemoveField(
                    model_name='user',
                    name='following',
                ),
                migrations.AddField(
                    model_name='user',
                    name='followed_users',
                    field=models.ManyToManyField(db_table='conduit_user_followed_users', to=settings.AUTH_USER_MODEL),
                )
            ]
        )
    ]
